apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-api-gateway
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=hello-api-gateway"
spec:
  type: service
  lifecycle: experimental
  owner: hello-team
  system: hello
  dependsOn: 
    - component:hello-service
