apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: hello-service
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Albertoimpl/spring-cloud-gateway-accelerator
      ref:
        branch: main
